### ISSUE TITLE
an error occured

### ISSUE THREAD

**Issue by gyewtools** [Pr0t0ns/Pr0t0n-Discord-Token-Generator#1]
an error occured creating 2cap task, same for hcoptcha im using residential rotating and i set it to show any errors but nun

**Comment by solroma** [comment]
+

**Comment by Pr0t0ns** [comment]
looking into it

**Comment by solroma** [comment]
![image](https://github.com/Pr0t0ns/Pr0t0n-Discord-Token-Generator/assets/60844626/92ea71c1-d110-415f-a258-044bc59bde96)

**Comment by solroma** [comment]
all Locked Tokens

**Comment by Pr0t0ns** [comment]
> all Locked Tokens

Thank you for confirming

**Comment by solroma** [comment]
why Locked Tokens?

**Comment by Pr0t0ns** [comment]
bad captcha responses
