### ISSUE TITLE
Help Me Too Fix It

### ISSUE THREAD

**Issue by MoonParadise** [Pr0t0ns/Pr0t0n-Discord-Token-Generator#6]
Users\Administrator\Downloads\Pr0t0n-Discord-Token-Generator-main\Pr0t0n-Discord-Token-Generator-main\main.py", line 12, in <module>
    import requests
  File "C:\Program Files\Python312\Lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Program Files\Python312\Lib\site-packages\urllib3\__init__.py", line 12, in <module>
    from logging import NullHandler
ImportError: cannot import name 'NullHandler' from 'logging' (C:\Users\Administrator\Downloads\Pr0t0n-Discord-Token-Generator-main\Pr0t0n-Discord-Token-Generator-main\logging.py)

How to fix

**Comment by Nixkkon** [comment]
same error

**Comment by Mouad-scriptz** [comment]
delete logging.py from the folder

**Comment by Nixkkon** [comment]
![image_2024-05-23_194514558](https://github.com/Pr0t0ns/Pr0t0n-Discord-Token-Generator/assets/155159564/1e0842a0-e8e8-49be-81bb-2117cd69fab1) says this now

**Comment by Nixkkon** [comment]
![Screenshot 2024-05-23 194330](https://github.com/Pr0t0ns/Pr0t0n-Discord-Token-Generator/assets/155159564/138c8f25-151f-48b6-8090-5bbb20c66439)
says this now

**Comment by Nixkkon** [comment]
somehow i fixed it, but it says error fetching cookies now.

**Comment by MoonParadise** [comment]
working now but i make locked token

**Comment by Pr0t0ns** [comment]
> somehow i fixed it, but it says error fetching cookies now.

proxy error
